servicesNamespace: lightningfaas-fn
authUser: oscar
authPass: password

serverlessBackend: ""

openfaas:
  namespace: openfaas
  port: 8080

service:
  type: NodePort
  port: 8080
  nodePort: 30301

replicas: 1

createIngress: false

image:
  repository: rajitha98/lightningfaas
  tag: "latest"
  pullPolicy: Always

readTimeout: 300
writeTimeout: 300

minIO:
  endpoint: https://minio-service.minio:9000
  TLSVerify: "true"
  region:  us-east-1
  accessKey: minio
  secretKey: password

volume:
  storageClassName: "nfs"
  supervisorVersion: "1.3.0"
  watchdogVersion: "0.18.10"

livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 15
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3


nodeSelector: {}
tolerations: []
affinity: {}

resources:
  requests:
    memory: 256Mi
    cpu: 250m