---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lightningfaas-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lightningfaas-controller
  namespace: {{ .Values.servicesNamespace | quote }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - podtemplates
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
{{- if ne .Values.serverlessBackend "" }}
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch
{{- end }}
{{- if eq (lower .Values.serverlessBackend) "openfaas" }}
- apiGroups:
  - openfaas.com
  resources:
  - functions
  verbs:
  - get
  - list
  - watch
  - create
  - delete
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lightningfaas-controller-binding
  namespace: {{ .Values.servicesNamespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lightningfaas-controller
subjects:
- kind: ServiceAccount
  name: lightningfaas-sa
  namespace: lightningfaas