{{- if .Values.createIngress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lightningfaas
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
        - backend:
            service:
              name: lightningfaas
              port:
                number: {{ .Values.service.port }}
          pathType: Prefix
          path: /
{{- end }}